use pyxmart_shop;

CREATE TABLE IF NOT EXISTS users(

id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(50) NOT NULL,
lastname VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
phone VARCHAR(20) DEFAULT NULL,
password VARCHAR(100) NOT NULL,
type ENUM('CUSTOMER', 'ADMIN') NOT NULL,
is_using_mfa BOOLEAN DEFAULT FALSE,
enabled BOOLEAN DEFAULT TRUE,
email_verified BOOLEAN DEFAULT FALSE,
account_locked BOOLEAN DEFAULT FALSE,
failed_login_attempts INT DEFAULT NULL,
last_login_at DATETIME DEFAULT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT NULL,
newsletter_subscribed BOOLEAN DEFAULT FALSE,
terms_accepted_at DATETIME DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS user_roles(
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
user_id BIGINT UNSIGNED NOT NULL,
role_id BIGINT UNSIGNED NOT NULL,
CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id),
CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id),
CONSTRAINT uk_user_role UNIQUE(user_id,role_id)
);

CREATE TABLE IF NOT EXISTS roles(
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 role_name VARCHAR(50) NOT NULL,
 CONSTRAINT uk_roles UNIQUE (role_name)
);



CREATE TABLE IF NOT EXISTS role_permissions(
  role_id BIGINT UNSIGNED NOT NULL,
  permission VARCHAR(50) NOT NULL,
  CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES roles(id),
  CONSTRAINT uk_role_permission UNIQUE (role_id,permission)
);

CREATE TABLE IF NOT EXISTS brands(
id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
description TEXT
);

CREATE TABLE IF NOT EXISTS categories (
id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
description TEXT ,
category_parent_id BIGINT UNSIGNED DEFAULT NULL,
CONSTRAINT fk_category_category_parent FOREIGN KEY (category_parent_id) REFERENCES categories(id)
);


CREATE TABLE IF NOT EXISTS products(
id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
code VARCHAR(100) NOT NULL,
slug VARCHAR(100) DEFAULT NULL,
short_description VARCHAR(100) NOT NULL,
description TEXT NOT NULL,
category_id BIGINT UNSIGNED NOT NULL,
brand_id BIGINT UNSIGNED NOT NULL,
product_status VARCHAR(30) NOT NULL,
featured BOOLEAN NOT NULL DEFAULT FALSE,
meta_title VARCHAR(100) DEFAULT NULL,
meta_description VARCHAR(100) DEFAULT NULL,
meta_keywords VARCHAR(100) DEFAULT NULL,
created_at DATETIME DEFAULT NULL,
updated_at DATETIME DEFAULT NULL,
published_at DATETIME DEFAULT NULL,
CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id),
CONSTRAINT fk_products_brand FOREIGN KEY (brand_id) REFERENCES brands(id)
);

CREATE TABLE IF NOT EXISTS vat_rates(
id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
rate DECIMAL(5,2) NOT NULL,
short_description VARCHAR(150) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS product_financials(
id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
product_id BIGINT UNSIGNED NOT NULL,
purchase_price DECIMAL(10,2) DEFAULT NULL,
selling_price DECIMAL(10,2) NOT NULL,
vat_rate_id BIGINT UNSIGNED NOT NULL,
CONSTRAINT fk_product_financial_product FOREIGN KEY (product_id) REFERENCES products(id),
CONSTRAINT fk_product_financial_vat FOREIGN KEY (vat_rate_id) REFERENCES vat_rates(id)
);




