use pyxmart_shop;

CREATE TABLE IF NOT EXISTS users(

id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(50) NOT NULL,
lastname VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
phone VARCHAR(20) NOT NULL,
password VARCHAR(100) NOT NULL,
type ENUM('CUSTOMER', 'ADMIN') NOT NULL,
enabled BOOLEAN DEFAULT TRUE,
email_verified BOOLEAN DEFAULT FALSE,
account_locked BOOLEAN DEFAULT FALSE,
failed_login_attempts INT DEFAULT NULL,
last_login_at DATETIME DEFAULT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT NULL,
newsletter_subscribed BOOLEAN DEFAULT FALSE,
terms_accepted_at DATETIME DEFAULT NULL
);