use pyxmart_shop;

CREATE TABLE IF NOT EXISTS users(

id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(50) NOT NULL,
lastname VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
phone VARCHAR(20) DEFAULT NULL,
password VARCHAR(100) NOT NULL,
type ENUM('CUSTOMER', 'ADMIN') NOT NULL,
is_using_mfa BOOLEAN DEFAULT FALSE,
enabled BOOLEAN DEFAULT TRUE,
email_verified BOOLEAN DEFAULT FALSE,
account_locked BOOLEAN DEFAULT FALSE,
failed_login_attempts INT DEFAULT NULL,
last_login_at DATETIME DEFAULT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT NULL,
newsletter_subscribed BOOLEAN DEFAULT FALSE,
terms_accepted_at DATETIME DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS user_roles(
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
user_id BIGINT UNSIGNED NOT NULL,
role_id BIGINT UNSIGNED NOT NULL,
CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id),
CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id),
CONSTRAINT uk_user_role UNIQUE(user_id,role_id)
);

CREATE TABLE IF NOT EXISTS roles(
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 role_name VARCHAR(50) NOT NULL,
 CONSTRAINT uk_roles UNIQUE (role_name)
);



CREATE TABLE IF NOT EXISTS role_permissions(
  role_id BIGINT UNSIGNED NOT NULL,
  permission VARCHAR(50) NOT NULL,
  CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES roles(id),
  CONSTRAINT uk_role_permission UNIQUE (role_id,permission)
);